name: build nodejs application continue to run the job
on: 
 workflow_dispatch:
 push:
  branches:
   -master
jobs:
  job1:
   continue-on-error: true
   strategy: 
    matrix:
     node-versiom: [12,16,18]
     operating-system: [ubuntu-latest,window-latest]
   runs-on: ${{ matrix.operating-system }}
   steps:
     - name: clone the repository
       uses: actions/checkout@v4
     - name: Install nodejs
       uses: actions/setup-node@v4
       with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
     - name: Install dependencies
       run: npm ci
     - name: Execute the test cases
       run: npm test
     - name: Build the code
       run: npm run build
     - name: Deploy the code
       run: echo "Deploy the code"
